version: 1
servers:
  prod :
      - name : "prod server #1"
        host : "localhost:22"
        user : "root"
  staging :
      - name : "staging server #1"
        host : "localhost:22"
        user : "ubuntu"
      - name : "staging server #2"
        host : "localhost:23"
        user : "ubuntu"
commands:
  whats_up :
      - "ls -al /tmp"
      - "date"
      - "date"
  date :
      - "date"