version: 1
servers:
  prod :
      - name : "prod server #1"
        host : "sdf.org:22"
        user : "new"
  staging :
      - name : "staging server #1"
        host : "localhost:22"
        user : "ubuntu"
      - name : "staging server #2"
        host : "localhost:23"
        user : "ubuntu"
commands:
  whats_up :
      - "date"
      - "date"
  date :
      - "date"